name: Run JWT compliance testsuite

on:
  push:
    branches: [ master ]

  schedule:
    - cron: '0 13 * * *'

jobs:
  run-testsuite:
    name: JWT compliance test suite

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup oidc-agent account
        run: |
          mkdir -p ${HOME}/.config/oidc-agent
          cp assets/.config/oidc-agent/* $HOME/.config/oidc-agent/

      - name: Fetch crls
        run: docker-compose up trust

      - name: Run testsuite
        env:
          OIDC_AGENT_SECRET: ${{ secrets.OIDC_AGENT_SECRET }}
          ROBOT_ARGS: --exclude strict
            # RUN_DEBUG: yes
        run: |
          mkdir -p reports && chmod 777 reports
          docker-compose up -d ts 
          docker-compose exec -T ts bash -c 'cd test-suite && sh ci/run.sh'
          docker-compose down

      - name: Archive reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports
          retention-days: 30
